export const BLOG_POSTS = [
    {
        id: "benefits-of-batana-oil",
        slug: "benefits-of-batana-oil",
        title: "The Science & Sourcing of Batana Oil",
        excerpt: "Discover why Honduran forest communities have relied on this rare kernel extract for centuries to protect and grow healthy, shiny hair.",
        category: "Ingredients",
        readTime: "5 min read",
        image: "/ingredients_hero.png",
        date: "June 24, 2026",
        author: "STORDS Editorial",
    },
    {
        id: "prevent-hair-breakage",
        slug: "prevent-hair-breakage",
        title: "5 Proven Rules to Stop Hair Breakage",
        excerpt: "Are you losing length to split ends and styling damage? Learn mechanical and hydration adjustments to increase tensile strength.",
        category: "Hair Education",
        readTime: "4 min read",
        image: "/hair_model.png",
        date: "June 18, 2026",
        author: "STORDS Editorial",
    },
    {
        id: "moisture-vs-growth",
        slug: "moisture-vs-growth",
        title: "Hair Moisture vs. Hair Growth: Explained",
        excerpt: "Many search for growth serums when the real challenge is moisture retention. We break down the differences and key routines.",
        category: "Science",
        readTime: "6 min read",
        image: "/ingredients_hero.png",
        date: "June 10, 2026",
        author: "STORDS Editorial",
    },
];
